### ISSUE TITLE
GetPot:1349:34: error: cannot convert bool to const char* in return

### ISSUE THREAD

**Issue by davidcarver** [siliu-tacc/slurm_showq#1]
Since g++ version 6 that C++14 is now the default; and  C++14 changed the definition of a null pointer constant so that only integer literals (and not integral constant expressions) qualify. false is a boolean literal, not an integer one, so under C++14, the code will not compile.

make[1]: Entering directory `/work/00108/dcarver/slurm_showq'
g++ -DHAVE_CONFIG_H -I.     -g -O2 -MT slurm_showq.o -MD -MP -MF .deps/slurm_showq.Tpo -c -o slurm_showq.o slurm_showq.cpp
In file included from slurm_showq.h:32,
                 from slurm_showq.cpp:30:
GetPot: In member function const char* GetPot::__match_starting_string(const char*):
GetPot:1349:34: error: cannot convert bool to const char* in return
     if( ! search_loop_f ) return false;
                                  ^~~~~
make[1]: *** [slurm_showq.o] Error 1
make[1]: Leaving directory `/work/00108/dcarver/slurm_showq'
make: *** [all] Error 2

login3$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/opt/apps/gcc/8.3.0/libexec/gcc/x86_64-pc-linux-gnu/8.3.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /admin/build/admin/rpms/frontera/BUILD/gcc-8.3.0/configure --enable-libssp --enable-gold=yes --enable-ld=default --enable-plugins --enable-lto --with-tune=generic --enable-languages=c,c++,fortran --disable-multilib --prefix=/opt/apps/gcc/8.3.0 --with-gmp=/opt/apps/gcc/8.3.0 --with-mlgmp=/opt/apps/gcc/8.3.0 --with-mpfr=/opt/apps/gcc/8.3.0 --with-mpc=/opt/apps/gcc/8.3.0 --with-isl=/opt/apps/gcc/8.3.0
Thread model: posix
gcc version 8.3.0 (GCC) 

I think the line
     if( ! search_loop_f ) return false;
should be
     if( ! search_loop_f ) return 0;

**Comment by siliu-tacc** [comment]
This has been updated in one of the early versions.

Thanks a lot,
Si
